# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea048d8a6a6f257db9be87e157a2c08dd79e3472d9ca082fba8e51cdd1ec7e71d04917423636b848e3ad5a890f27e4166a03c8c87f7ee231412eea3cf34ebb7f

test:
  secret_key_base: 810cdc4509cd7594fc72f66da26c7b94cbb9147e0a2e599e9c03266b5e66b2706e103ad7960760fd09e0523aea3cd0e6f295d77ad51f1ba71e7eef577ebf7861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
